{% set name = "coiled" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 346b39bb6d09fda29c70cc5597c8ce1fc93e2efbd93a51b1b60b1c66080c7501

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aiohttp
    - aiobotocore >=0.12.0,<0.13
    - click
    - distributed >=2.19.0

test:
  requires:
    - pip
  commands:
    - pip check
    - coiled env create --help
    - coiled login --help
  imports:
    - coiled

about:
  home: https://coiled.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Deploy Dask cluster using Coiled Cloud

  description: |
    A Python package to easily create, manage, and connect to Dask deployments
    using Coiled Cloud.
  doc_url: https://coiled.io/cloud

extra:
  recipe-maintainers:
    - jrbourbeau
    - mrocklin
