{% set name = "coiled" %}
{% set version = "0.0.36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da1f18ae3d50e9e4c948663a95c5db8ffeee6717f5839cda014a7c1f0328266d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aiohttp
    - aiobotocore >=1.1.1
    - boto3
    - click
    - dask >=2.23.0
    - s3fs
    - pandas >=1.1.0
    - ipython

test:
  requires:
    - pip
  commands:
    - pip check
    - coiled install --help
    - coiled login --help
    - coiled env --help
    - coiled --version
  imports:
    - coiled

about:
  home: https://coiled.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Deploy Dask cluster using Coiled Cloud

  description: |
    A Python package to easily create, manage, and connect to Dask deployments
    using Coiled Cloud.
  doc_url: https://coiled.io/cloud

extra:
  recipe-maintainers:
    - jrbourbeau
    - mrocklin
